config/routes.rb
Rails.application.routes.draw do
  resources :videos

  get 'pages/about'

  get 'pages/contact'

  root 'videos#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
	def next
		Video.where("id > ?", id).first 
	end	

	def prev
		Video.where("id < ?", id).last
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @videos = Video.all

    @next_video = @video.next
    @prev_video = @video.prev
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectHero</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>
          
  
</head>
<body>

  <nav>
    <div class="nav-wrapper pink darken-2">
      <%= link_to "PracticalSchmactical", root_path, :class => "brand-logo" %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="<%= root_path %>"><i class="mdi-action-view-list"></i> </a> </li>
        <li><a href="<%= pages_about_path %>"><i class="mdi-action-face-unlock"></i> </a> </li>
        <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i> </a> </li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="<%= root_path %>"><i class="mdi-action-view-list"></i> </a> </li>
        <li><a href="<%= pages_about_path %>"><i class="mdi-action-face-unlock"></i> </a> </li>
        <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i> </a> </li>
      </ul>
    </div>
  </nav>

  <div class="row">
    <div class="col m10 offset-m1"> <!-- Centres and sets to 10/12 columns -->
      <%= yield %>
    </div>
  </div>



<script> $(".button-collapse").sideNav();</script>

</body>
</html>

app/views/pages/about.html.erb
<div class="card z-depth-3">
	<div class="card-content white-text">
		<div class="col m4">
			<a class="twitter-timeline" href="https://twitter.com/seonaid_lee" data-widget-id="605421579892322305">Tweets by @seonaid_lee</a>
			
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
			</script>
			
		</div>	
		<div class="col m8">
			<div class="card-panel grey lighten-5 z-depth-1">
				<div class="row valign-wrapper">
					<div class="col m3">
						<%= image_tag "avatar.png", class: "circle responsive-img" %>
					</div>
					<div class="col m9">
						<span class = "black-text">
							In which I attempt the impossible: turning decades of academic training into income by making them into art.
							In gathering together all the things... do they become coherent?
						</span>
					</div>

				</div>
				<div class="row">
				<div class="col m6">
					<!-- start feedwind code --><script type="text/javascript">document.write('\x3Cscript type="text/javascript" src="' + ('https:' == document.location.protocol ? 'https://' : 'http://') + 'feed.mikle.com/js/rssmikle.js">\x3C/script>');</script><script type="text/javascript">(function() {var params = {rssmikle_url: "http://figuresthingsout.com/rss",rssmikle_frame_width: "300",rssmikle_frame_height: "400",frame_height_by_article: "0",rssmikle_target: "_blank",rssmikle_font: "Arial, Helvetica, sans-serif",rssmikle_font_size: "12",rssmikle_border: "on",responsive: "on",rssmikle_css_url: "",text_align: "left",text_align2: "left",corner: "on",scrollbar: "on",autoscroll: "off",scrolldirection: "up",scrollstep: "3",mcspeed: "20",sort: "Off",rssmikle_title: "on",rssmikle_title_sentence: "",rssmikle_title_link: "",rssmikle_title_bgcolor: "#0066FF",rssmikle_title_color: "#FFFFFF",rssmikle_title_bgimage: "",rssmikle_item_bgcolor: "#FFFFFF",rssmikle_item_bgimage: "",rssmikle_item_title_length: "55",rssmikle_item_title_color: "#0066FF",rssmikle_item_border_bottom: "on",rssmikle_item_description: "on",item_link: "off",rssmikle_item_description_length: "150",rssmikle_item_description_color: "#666666",rssmikle_item_date: "gl1",rssmikle_timezone: "Etc/GMT",datetime_format: "%b %e, %Y %l:%M:%S %p",item_description_style: "text+tn",item_thumbnail: "full",item_thumbnail_selection: "auto",article_num: "15",rssmikle_item_podcast: "off",keyword_inc: "",keyword_exc: ""};feedwind_show_widget_iframe(params);})();</script><div style="font-size:10px; text-align:center; "><a href="http://feed.mikle.com/" target="_blank" style="color:#CCCCCC;">RSS Feed Widget</a><!--Please display the above link in your web page according to Terms of Service.--></div><!-- end feedwind code -->
				</div>
<div class="col m6">
<!-- start feedwind code --><script type="text/javascript">document.write('\x3Cscript type="text/javascript" src="' + ('https:' == document.location.protocol ? 'https://' : 'http://') + 'feed.mikle.com/js/rssmikle.js">\x3C/script>');</script><script type="text/javascript">(function() {var params = {rssmikle_url: "http://thepracticaldilettante.com/rss",rssmikle_frame_width: "300",rssmikle_frame_height: "400",frame_height_by_article: "0",rssmikle_target: "_blank",rssmikle_font: "Arial, Helvetica, sans-serif",rssmikle_font_size: "12",rssmikle_border: "on",responsive: "on",rssmikle_css_url: "",text_align: "left",text_align2: "left",corner: "on",scrollbar: "on",autoscroll: "off",scrolldirection: "up",scrollstep: "3",mcspeed: "20",sort: "Off",rssmikle_title: "on",rssmikle_title_sentence: "",rssmikle_title_link: "",rssmikle_title_bgcolor: "#0066FF",rssmikle_title_color: "#FFFFFF",rssmikle_title_bgimage: "",rssmikle_item_bgcolor: "#FFFFFF",rssmikle_item_bgimage: "",rssmikle_item_title_length: "55",rssmikle_item_title_color: "#0066FF",rssmikle_item_border_bottom: "on",rssmikle_item_description: "on",item_link: "off",rssmikle_item_description_length: "150",rssmikle_item_description_color: "#666666",rssmikle_item_date: "gl1",rssmikle_timezone: "Etc/GMT",datetime_format: "%b %e, %Y %l:%M:%S %p",item_description_style: "text+tn",item_thumbnail: "full",item_thumbnail_selection: "auto",article_num: "15",rssmikle_item_podcast: "off",keyword_inc: "",keyword_exc: ""};feedwind_show_widget_iframe(params);})();</script><div style="font-size:10px; text-align:center; "><a href="http://feed.mikle.com/" target="_blank" style="color:#CCCCCC;">RSS Feed Widget</a><!--Please display the above link in your web page according to Terms of Service.--></div><!-- end feedwind code -->
				</div>

			</div>
			<div class="row">
					<div class="col m6">
						<!-- start feedwind code --><script type="text/javascript">document.write('\x3Cscript type="text/javascript" src="' + ('https:' == document.location.protocol ? 'https://' : 'http://') + 'feed.mikle.com/js/rssmikle.js">\x3C/script>');</script><script type="text/javascript">(function() {var params = {rssmikle_url: "http://mappingtheuniverse.wordpress.com/?rss",rssmikle_frame_width: "300",rssmikle_frame_height: "400",frame_height_by_article: "0",rssmikle_target: "_blank",rssmikle_font: "Arial, Helvetica, sans-serif",rssmikle_font_size: "12",rssmikle_border: "on",responsive: "on",rssmikle_css_url: "",text_align: "left",text_align2: "left",corner: "on",scrollbar: "on",autoscroll: "off",scrolldirection: "up",scrollstep: "3",mcspeed: "20",sort: "Off",rssmikle_title: "on",rssmikle_title_sentence: "",rssmikle_title_link: "",rssmikle_title_bgcolor: "#0066FF",rssmikle_title_color: "#FFFFFF",rssmikle_title_bgimage: "",rssmikle_item_bgcolor: "#FFFFFF",rssmikle_item_bgimage: "",rssmikle_item_title_length: "55",rssmikle_item_title_color: "#0066FF",rssmikle_item_border_bottom: "on",rssmikle_item_description: "on",item_link: "off",rssmikle_item_description_length: "150",rssmikle_item_description_color: "#666666",rssmikle_item_date: "gl1",rssmikle_timezone: "Etc/GMT",datetime_format: "%b %e, %Y %l:%M:%S %p",item_description_style: "text+tn",item_thumbnail: "full",item_thumbnail_selection: "auto",article_num: "15",rssmikle_item_podcast: "off",keyword_inc: "",keyword_exc: ""};feedwind_show_widget_iframe(params);})();</script><div style="font-size:10px; text-align:center; "><a href="http://feed.mikle.com/" target="_blank" style="color:#CCCCCC;">RSS Feed Widget</a><!--Please display the above link in your web page according to Terms of Service.--></div><!-- end feedwind code -->
					</div>
			</div>

</div>
		</div>
	</div>
</div>

app/views/pages/contact.html.erb
<h3>Contact</h3>

<div class="card z-depth-3">
	<div class="card-content">
		This is where I hang out: <br/>
		<div id="map-canvas"></div>
	</div>
</div>

<style>
  #map-canvas {
    width: 100%;
    height: 400px;
  }
</style>

<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
  function initialize() {
    var mapCanvas = document.getElementById('map-canvas');
    var mapOptions = {
      center: new google.maps.LatLng(46.1432, -60.1964),
      zoom: 14,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(mapCanvas, mapOptions)
    var marker = new google.maps.Marker({
    	position: new google.maps.LatLng(46.1432, -60.1964),
    	title: "UIT-ish"
    });

    marker.setMap(map);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.text_field :wistia, :placeholder => 'link', :length => '10' %>
  </div>
    <div class="input-field">
    <%= f.text_field :title, :placeholder => 'title', :length => '20'  %>
  </div>
  <div class="input-field">
    <%= f.text_area :description, :placeholder => 'description', :length => '800', :class => 'materialize-textarea'  %>
  </div>
  <button class="btn waves-effects waves-light" type = "submit" name = "action">
    Submit
  </button>
  <a href="<%= videos_path %>" class = "btn waves-effect waves-light" name = "action">Back</a>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<div class="card">
	<div class="card-content">
		<%= render 'form' %> <!-- includes form partial -->
	</div>	
</div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Videos</h1>

<%= link_to new_video_path, :class => 'btn-floating btn waves-effect waves-light pink darken-1' do %>
  <i class = "mdi-content-add"></i>
<% end %>

<ul class = "collapsible" data-collapsible = "accordion">
  <% @videos.each do |video| %>
    <li>
      <div class="collapsible-header">
        <i class = "mdi-av-my-library-books"></i>
        <%= link_to video.title, video  %>
        <span class = "right">
          <%= link_to edit_video_path(video) do %>
            <i class = "mdi-content-create"></i>
          <% end %>
          <%= link_to video, method: :delete, data: { confirm: 'Are you sure?'} do %>
            <i class = "mdi-notification-event-busy"></i>
          <% end %>
        </span>
      </div>
      <div class="collapsible-body"> <p><%= video.description %></p> </div>
    </li>
  <% end %>
</ul>

app/views/videos/new.html.erb
<h1>New Video</h1>

<div class="card">
	<div class="card-content">
		<%= render 'form' %> <!-- includes form partial -->
	</div>	
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col m3">
      <div class="collection">
      	<% @videos.each do |video| %>
      		<%= link_to video.title, video, :class => 'collection-item' %>
      	<% end %>
      </div>
	</div>

	<div class="col m9">
		<div class="card indigo darken-2 z-depth-2">
			<div class="card-image">
				<div id="player"></div>
			</div>

			<div class="card-content white-text">
				<button class = "btn btn-primary" onclick = "setPlaySpeed(0.75)" >0.75x</button>
				<button class = "btn btn-primary" onclick = "setPlaySpeed(1)" >1x</button>
				<button class = "btn btn-primary" onclick = "setPlaySpeed(1.25)" >1.25x</button>
				<button class = "btn btn-primary" onclick = "setPlaySpeed(1.5)" >1.5x</button>
				<button class = "btn btn-primary" onclick = "setPlaySpeed(2)" >2x</button>
				<br>
				<span class="card-title"><%= @video.title %></span>
				<p><%= @video.description %></p>
			</div>
			
			<div class="card-action">
				<%= link_to "Previous", @prev_video if !@prev_video.nil? %>
				<span class = "right">
					<%= link_to "Next", @next_video if !@next_video.nil? %>
				</span>
			</div>
		</div>
	</div>
</div>

    <script>
      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
			width: '100%',
          videoId: '<%= @video.wistia %>',
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.playVideo();
      }

      // This is my own code, based on the code for Wistia in Leo's tutorial
      function setPlaySpeed(speed){
      	player.setPlaybackRate(speed);
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          setTimeout(stopVideo, 6000);
          done = true;
        }
      }
      function stopVideo() {
        player.stopVideo();
      }
    </script>